---
- hosts: all # part running on all hosts
  become: true
  tasks:

  - name: Add docker repository
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docer-ce.repo
    become: yes

  - name: install packages
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io 
      - docker-buildx-plugin 
      - docker-compose-plugin

  - name: ensure docker is running and enabled
    systemd:
      name: docker
      state: restarted
      enabled: yes

  - name: copy Dockerfile
    copy:
      src: files/Dockerfile
      dest: /home/vagrant/Dockerfile
      owner: root
      group: root
      mode: 0644

  - name: copy default.conf
    copy:
      src: files/default.conf
      dest: /home/vagrant/default.conf
      owner: root
      group: root 
      mode: 0644

  - name: copy index3000.html
    copy:
      src: files/index3000.html
      dest: /home/vagrant/index3000.html
      owner: root
      group: root 
      mode: 0644

  - name: copy index80.html
    copy:
      src: files/index80.html
      dest: /home/vagrant/index80.html
      owner: root
      group: root 
      mode: 0644

  - name: Buid and start docker-container
    shell: 'cd /home/vagrant && docker build -t my-nginx . && docker run -p 80:80 -p 3000:3000 -dt my-nginx'
