---
- hosts: all # part running on all hosts
  become: true
  tasks:

  - name: copy timezone
    copy:
      src: /usr/share/zoneinfo/Europe/Moscow
      dest: /etc/localtime
      owner: root

  - name: restart chronyd
    systemd:
      name: chronyd
      state: restarted
      enabled: yes

  - name: install packages
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - mc
      - nano

- hosts: Server-Nginx # part running on all hosts
  become: true
  tasks:

  - name: Install EPEL repo.
    yum: name=epel-release state=present
    become: yes

  - name: install packages
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - nginx
      - audispd-plugins
      - rsyslog

  - name: copy nginx.conf
    copy:
      src: files/nginx.conf
      dest: /etc/nginx/nginx.conf
      owner: root

  - name: restart nginx
    systemd:
      name: nginx
      state: restarted
      enabled: yes

  - name: copy auditd.conf
    copy:
      src: files/auditd.conf
      dest: /etc/audit/auditd.conf
      owner: root

  - name: copy au-remote.conf
    copy:
      src: files/au-remote.conf
      dest: /etc/audit/plugins.d/au-remote.conf
      owner: root

  - name: copy audisp-remote.conf
    copy:
      src: files/audisp-remote.conf
      dest: /etc/audit/audisp-remote.conf
      owner: root

  - name: copy nginx.rules
    copy:
      src: files/nginx.rules
      dest: /etc/audit/rules.d/nginx.rules
      owner: root

  - name: copy audit.conf
    copy:
      src: files/audit.conf
      dest: /etc/rsyslog.d/audit.conf
      owner: root

  - name: restart auditd
    command: /sbin/setenforce 0

  - name: restart rsyslog
    systemd:
      name: rsyslog
      state: restarted
      enabled: yes

  - name: restart auditd
    command: /sbin/service auditd restart

- hosts: Server-Logs # part running on all hosts
  become: true
  tasks:

  - name: install packages
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - rsyslog

  - name: copy rsyslog.conf
    copy:
      src: files/rsyslog.conf
      dest: /etc/rsyslog.conf
      owner: root
      group: root
      mode: 0644

  - name: restart rsyslog
    systemd:
      name: rsyslog
      state: restarted
      enabled: yes
